# Funding configuration for ComfyUI-Copilot
# This project is part of the ComfyUI ecosystem and welcomes financial support

github: [AIDC-AI]  # Organization GitHub Sponsors
open_collective: comfyui-copilot  # Future Open Collective (create if needed)
ko_fi: comfyui_copilot  # Ko-fi username (create if needed)
liberapay: comfyui_copilot  # LiberaPay username (create if needed)

# Custom funding links
custom:
  - 'https://floss.fund/apply'  # FLOSS/fund application
  - 'https://opencollective.com/comfyui-copilot'  # Future Open Collective
  - 'https://github.com/sponsors/AIDC-AI'  # GitHub Sponsors
  - 'https://www.buymeacoffee.com/comfyui_copilot'  # Buy Me A Coffee (create if needed)

# Note: To apply for FLOSS/fund, visit: https://floss.fund/apply
# The application should highlight the project's impact on the open-source AI ecosystem
